### ISSUE TITLE
Trouble building on mac

### ISSUE THREAD

**Issue by positlabs** [lostjared/acidcam-cli#4]
I'm not too familiar with compiling C++, but I installed the dependencies and ran the build command. It's failing with some errors that suggest syntax issues.

<img width="661" alt="Screen Shot 2019-05-10 at 1 40 10 PM" src="https://user-images.githubusercontent.com/1918844/57545765-5ba67600-7329-11e9-82b7-68738ed6d892.png">

If I can get this working, I am going to try to compile with webassembly (just for fun, really).

**Comment by lostjared** [comment]
I fixed the issue I had not checked with metacall disabled it should compile now.

**Comment by positlabs** [comment]
Perfect. Confirmed it is working now.
