### ISSUE TITLE
GUI?

### ISSUE THREAD

**Issue by positlabs** [lostjared/acidcam-cli#5]
Is there a gui for acidcam anywhere? Might be cool to make an electron app.

**Comment by lostjared** [comment]
check here for macOS GUI: https://github.com/lostjared/Acid.Cam.v2.OSX
here for Cross platform Qt: https://github.com/lostjared/Acid.Cam.v2.Qt

**Comment by positlabs** [comment]
Rad, cloning them now! Thanks!
