### ISSUE TITLE
Help compile on linux

### ISSUE THREAD

**Issue by vjx** [lostjared/acidcam-cli#7]
Hello, I am getting errors when I run make:

> make -j4
make  all-recursive
make[1]: Entering directory '/home/x/Documents/acidcam-cli'
Making all in acidcam
make[2]: Entering directory '/home/x/Documents/acidcam-cli/acidcam'
g++ -DHAVE_CONFIG_H -I. -I..  -O2 -std=c++11   -I/usr/include/opencv -I@DEST_DIR@/include/acidcam -I@DEST_DIR@/include    -g -O2 -MT acidcam-cli.o -MD -MP -MF .deps/acidcam-cli.Tpo -c -o acidcam-cli.o acidcam-cli.cpp
g++ -DHAVE_CONFIG_H -I. -I..  -O2 -std=c++11   -I/usr/include/opencv -I@DEST_DIR@/include/acidcam -I@DEST_DIR@/include    -g -O2 -MT acidcam-cli-main.o -MD -MP -MF .deps/acidcam-cli-main.Tpo -c -o acidcam-cli-main.o acidcam-cli-main.cpp
In file included from acidcam-cli.cpp:43:0:
acidcam-cli.hpp:45:9: fatal error: ac.h: No such file or directory
 #include"ac.h"
         ^~~~~~
compilation terminated.
In file included from acidcam-cli-main.cpp:43:0:
acidcam-cli.hpp:45:9: fatal error: ac.h: No such file or directory
 #include"ac.h"
         ^~~~~~
compilation terminated.
Makefile:393: recipe for target 'acidcam-cli.o' failed
make[2]: *** [acidcam-cli.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:393: recipe for target 'acidcam-cli-main.o' failed
make[2]: *** [acidcam-cli-main.o] Error 1
make[2]: Leaving directory '/home/x/Documents/acidcam-cli/acidcam'
Makefile:388: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/x/Documents/acidcam-cli'
Makefile:329: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lostjared** [comment]
you need to compile and install libacidcam https://github.com/lostjared/libacidcam

**Comment by vjx** [comment]
Well, I tough I did install:

> sudo make install
Making install in source
make[1]: Entering directory '/home/x/Documents/libacidcam/source'
make[2]: Entering directory '/home/x/Documents/libacidcam/source'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   libacidcam.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libacidcam.so.0.0.1 /usr/local/lib/libacidcam.so.0.0.1
libtool: install: (cd /usr/local/lib && { ln -s -f libacidcam.so.0.0.1 libacidcam.so.0 || { rm -f libacidcam.so.0 && ln -s libacidcam.so.0.0.1 libacidcam.so.0; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libacidcam.so.0.0.1 libacidcam.so || { rm -f libacidcam.so && ln -s libacidcam.so.0.0.1 libacidcam.so; }; })
libtool: install: /usr/bin/install -c .libs/libacidcam.lai /usr/local/lib/libacidcam.la
libtool: install: /usr/bin/install -c .libs/libacidcam.a /usr/local/lib/libacidcam.a
libtool: install: chmod 644 /usr/local/lib/libacidcam.a
libtool: install: ranlib /usr/local/lib/libacidcam.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /usr/local/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/usr/local/include/acidcam'
 /usr/bin/install -c -m 644 ac.h fractal.h ac-filtercat.h '/usr/local/include/acidcam'
 /bin/mkdir -p '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 ../acidcam.pc '/usr/local/lib/pkgconfig'
make[2]: Leaving directory '/home/x/Documents/libacidcam/source'
make[1]: Leaving directory '/home/x/Documents/libacidcam/source'
make[1]: Entering directory '/home/x/Documents/libacidcam'
make[2]: Entering directory '/home/x/Documents/libacidcam'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/x/Documents/libacidcam'
make[1]: Leaving directory '/home/x/Documents/libacidcam'

**Comment by vjx** [comment]
But if I make ctest it says No test configuration file found!

**Comment by lostjared** [comment]
I would recommend using cmake not autotools

download libacidcam
enter directory:

$ mkdir build  && cd build
$ cmake ..
$ make -j4 
$ sudo make install

download acidcam-cli:
enter directory

$ mkdir build && cd build
$ cmake ..
$ make -j4
$ sudo make install

use acidcam-cli

$ acidcam-cli -l

$ acidcam-cli -i input.mp4 -o mp4 -f 1

**Comment by lostjared** [comment]
Here is a better example of using acidcam-cli: (from the README)

Example:

$ acidcam-cli -i input.mov -o output.mov -f 1,2,3
or resize video

$ acidcam-cli -i input.mov -o output.mov -f 1,2,3 -u 1920x1080
use a subfiler give the index number followed by a colon and the subfilter it will use like this:

$ acidcam-cli -i input.mov -o output.mov -f 962:3
to use a subfilter and other files use:

$ acidcam-cli -i input.mov -o output.mov -f 962:0,10,5
or to view progress:

$ acidcam-cli -i input.mov -o output.mov -f 0 -v
to list filters:

$ acidcam-cli -l
to list plugins:

$ acidcam-cli -x
to use plugin:

$ acidcam-cli -i input.mov -o output.mov -p path/to/shared.acf -f plugin
or use:

$ acidcam-cli -x

**Comment by vjx** [comment]
It works.
Thanks a lot!

**Comment by lostjared** [comment]
Cool your welcome ill close this issue.
