### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by flyingmonkeycollective** [lostjared/acidcam-cli#8]
:~/Projectos/Acid_cam/acidcam-cli/build$ make -j4
Scanning dependencies of target acidcam-cli
[ 33%] Building CXX object CMakeFiles/acidcam-cli.dir/acidcam/acidcam-cli-main.cpp.o
[ 66%] Building CXX object CMakeFiles/acidcam-cli.dir/acidcam/acidcam-cli.cpp.o
[100%] Linking CXX executable acidcam-cli
/usr/bin/ld: CMakeFiles/acidcam-cli.dir/acidcam/acidcam-cli.cpp.o: in function `cmd::AC_Program::initProgram(cmd::File_Type const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::pair<int, int>, std::allocator<std::pair<int, int> > >&, std::vector<std::pair<int, int>, std::allocator<std::pair<int, int> > >&, int)':
acidcam-cli.cpp:(.text+0x2096): undefined reference to `open_ffmpeg(char const*, char const*, char const*, char const*, char const*, char const*)'
/usr/bin/ld: CMakeFiles/acidcam-cli.dir/acidcam/acidcam-cli.cpp.o: in function `cmd::AC_Program::run()':
acidcam-cli.cpp:(.text+0x39cb): undefined reference to `write_ffmpeg(_IO_FILE*, cv::Mat&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/acidcam-cli.dir/build.make:148: acidcam-cli] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/acidcam-cli.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

I have compiled the libacidcam without any apparent problems.
Followed this: 
download libacidcam
enter directory:

$ mkdir build && cd build
$ cmake ..
$ make -j4
$ sudo make install

download acidcam-cli:
enter directory

$ mkdir build && cd build
$ cmake ..
$ make -j4
$ sudo make install

**Comment by lostjared** [comment]
Solved this issue i forgot to add ffmpeg_write.cpp to CMake config txt file.
